services:
  fix-client:
    build: .
    container_name: ntpro-fix-client
    restart: unless-stopped
    volumes:
      - ./store:/app/store
      - ./log:/app/log
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
